Issue-7: Pass Manager
vorpal-research/kfg pull request #24
Opened 2022-07-14 15:56 UTC by rapturemain

2022-07-29 16:03 UTC, AbdullinAM requested changes

2022-07-29 16:03 UTC, AbdullinAM commented on pom.xml
> +            <artifactId>kotlin-compile-testing</artifactId>
Если это используется только в тестах, то лучше выставить `<scope>test</scope>`

2022-07-29 16:03 UTC, AbdullinAM commented on pom.xml
> +            <version>1.4.8</version>
Версии лучше вынести в проперти

2022-07-29 18:37 UTC, rapturemain commented on src/main/kotlin/org/vorpal/research/kfg/visitor/Pipeline.kt
> +            log.warn("Tried to schedule visitor ${visitor.name}, but not required constructor found. Assuming user will add an instance manually")
We cannot throw an exception here because it is assumed to be a valid case.\ 
For example if an user first schedules visitor `A` via `schedule<A>()`, which has a dependency on visitor `B`, then pipeline tries to schedule visitor `B`. But because visitor `B` has additional arguments in the constructor, pipeline fails and assumes user will add the visitor via `schedule(B(cm, pipeline, *args))`

2022-08-15 08:50 UTC, AbdullinAM approved these changes

2022-08-15 08:51 UTC, merged